[package]
name = "deepseek-ocr-server"
version = "0.2.0"
edition = "2024"

[dependencies]
base64 = "0.22"
rocket = { version = "0.5.0", features = ["json"] }
uuid = { version = "1.8", features = ["v4"] }
thiserror = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
tokio-stream = "0.1"
regex = "1.10"
imageproc = "0.25"
rusttype = "0.9"
anyhow = { workspace = true }
clap = { workspace = true }
image = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
deepseek-ocr-core = { workspace = true }
deepseek-ocr-assets = { workspace = true }
tokenizers = { workspace = true }
candle-core = { workspace = true }

[features]
default = []
metal = ["deepseek-ocr-core/metal"]
flash-attn = ["deepseek-ocr-core/flash-attn"]
cuda = ["deepseek-ocr-core/cuda"]
